name: Rust

on:
  push:
    tags:
      - 'v*' # v1.0，v20.15.10

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --release
